server:
  port: 8080
  servlet:
    context-path: /tshust_db

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tshust_db"
    username: root
    password: root

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true